# Generated by Django 4.1.2 on 2022-10-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_question_choosed_anwser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='option',
            name='option_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='option',
            name='option_4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_1',
            field=models.CharField(default='', max_length=50),
        ),
    ]
