# Generated by Django 4.1.2 on 2022-10-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_option_option_2_option_option_3_option_option_4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question_related',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answer_given',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='option_1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='option_2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='option_3',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='option_4',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='CorrectOption',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
