# Generated by Django 4.1.2 on 2022-10-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_remove_option_question_related_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateField(default= '1111-11-11'),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.TimeField(default=''),
        ),
    ]
