# Generated by Django 4.1.2 on 2022-10-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_test_date_alter_test_end_time_alter_test_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=0),
        ),
    ]
