# Generated by Django 4.1.2 on 2022-10-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.TimeField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.TimeField(default='0000-00-00'),
        ),
    ]
