# Generated by Django 4.1.2 on 2022-10-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_test_end_time_alter_test_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.TimeField(default=0),
        ),
    ]
