# Generated by Django 4.1.2 on 2022-10-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_remove_test_date_remove_test_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateField(blank=True, default='1111-11-11'),
        ),
        migrations.AddField(
            model_name='test',
            name='end_time',
            field=models.TimeField(blank=True, default='11:11:11.111111'),
        ),
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.TimeField(blank=True, default='11:11:11.111111'),
        ),
    ]
