# Generated by Django 4.1.2 on 2022-10-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_remove_test_date_remove_test_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_created',
            field=models.DateField(blank=True, default='', null=True),
        ),
    ]
