# Generated by Django 4.1.2 on 2022-10-19 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_course_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateTimeField(blank=True, default='1111-11-11', null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='end_time',
            field=models.TimeField(blank=True, default='11:11:11.111111'),
        ),
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.TimeField(blank=True, default='11:11:11.111111'),
        ),
    ]
