# Generated by Django 4.1.2 on 2022-10-19 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_test_date_test_end_time_test_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='date',
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 10, 19, 6, 36, 22, 33984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 10, 19, 6, 36, 22, 33677, tzinfo=datetime.timezone.utc)),
        ),
    ]
