# Generated by Django 4.1.2 on 2022-10-19 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_remove_test_date_alter_test_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='date',
            field=models.DateTimeField(blank=True, default='1111-11-11', null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 10, 19, 6, 37, 32, 229861, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 10, 19, 6, 37, 32, 229590, tzinfo=datetime.timezone.utc)),
        ),
    ]
