# Generated by Django 4.1.2 on 2022-10-19 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_test_date_alter_test_end_time_alter_test_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 10, 19), null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='end_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 10, 19, 6, 38, 54, 929172, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 10, 19, 6, 38, 54, 928872, tzinfo=datetime.timezone.utc)),
        ),
    ]
