# Generated by Django 4.1.2 on 2022-10-19 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_alter_test_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='given_by',
            new_name='given_to',
        ),
    ]
