# Generated by Django 4.1.2 on 2022-10-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_sid_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.IntegerField(default=0),
        ),
    ]
