# Generated by Django 4.1.2 on 2022-10-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_student_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isEnable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
