# Generated by Django 4.1.2 on 2022-10-17 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_student_isenable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='isEnable',
            new_name='disabled',
        ),
    ]
